apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities

resources:
  - deploy.yml
  - rbac.yml
  - ingress.yml

secretGenerator:
  - env: secret/one.env
    name: one-env
  - files:
      - secret/conf.yml
    name: one-config
  - files:
      - secret/oauth.github.json
    name: one-github-oauth

configMapGenerator:
  - env: one_config.env
    name: one-config-env
